[package]
name = "qos-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intervallum = "1.4.1"
bincode = "1.3.3"
serde = "1.0.149"