name = "benchmark/allreduce"
group = "allreduce"

[[worker]]
host = "danyang-03"
bin = "mccs"
args = "--host 3"
dependencies = []

[[worker]]
host = "danyang-04"
bin = "mccs"
args = "--host 4"
dependencies = []

[[worker]]
host = "danyang-03"
bin = "allreduce_bench"
args = "--root-addr 192.168.211.66 --rank 0 --num-ranks 2 --cuda-device-idx 0 --size 128 --communicator 42 --round 10"
dependencies = [0, 1]

[[worker]]
host = "danyang-04"
bin = "allreduce_bench"
args = "--root-addr 192.168.211.66 --rank 1 --num-ranks 2 --cuda-device-idx 0 --size 128 --communicator 42 --round 10"
dependencies = [0, 1]